### ISSUE TITLE
callback for ignoring geolocation request?

### ISSUE THREAD

**Issue by Jakobud** [estebanav/javascript-mobile-desktop-geolocation#3]
When Chrome or Firefox ask to give geolocation permission, you can either Allow or Deny OR just close the dialog, neither allowing or denying.  Is there a callback for this action?

**Comment by cpeeyush** [comment]
I don't think that geo location api has an call back or status for just closing the info bar or as you said dialog.

It only has 3 error codes:

PERMISSION_DENIED (1) if the user clicks that “Don’t Share” button or otherwise denies you access to their location.
POSITION_UNAVAILABLE (2) if the network is down or the positioning satellites can’t be contacted.
TIMEOUT (3) if the network is up but it takes too long to calculate the user’s position. How long is “too long”? I’ll show you how to define that in the next section.

You can keep a variable in your js with a default value something like "Location Not Detect Yet" & update it based on the Allow or Deny action so that you can identify whats happening.

**Comment by estebanav** [comment]
thanks @cpeeyush for the clarification to @Jakobud
